version: '3'
services:
  app:
    env_file: ./.env
    tty: true
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: 'python3'
    working_dir: '/root/src'
    volumes:
      - ./src:/root/src